name: Docker Image CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build g3
        run: |
          docker build ursim/g3 --tag ${{secrets.DOCKER_USER}}/ursim_docker:ursim_g3
      - name: Push g3
        run: |
          docker push ${{secrets.DOCKER_USER}}/ursim_docker:ursim_g3
      - name: Build g5
        run: |
          docker build ursim/g5 --tag ${{secrets.DOCKER_USER}}/ursim_docker:ursim_g5
      - name: Push g5
        run: |
          docker push ${{secrets.DOCKER_USER}}/ursim_docker:ursim_g5      
