name: e-series Image CI

on: 
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Build dockerfile
        run: |
          docker build ursim/e-series --build-arg VERSION=$VERSION --build-arg URSIM=$URSIM
        env:
          VERSION: 5.11.1.108318
          URSIM: "https://s3-eu-west-1.amazonaws.com/ur-support-site/118926/URSim_Linux-5.11.1.108318.tar.gz"

  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: |
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build dockerfile
        run: |
          docker build ursim/e-series --build-arg VERSION=$VERSION --build-arg URSIM=$URSIM --tag ${{secrets.DOCKER_USER}}/ursim_docker:$VERSION
        env:
          VERSION: 5.11.1.108318
          URSIM: "https://s3-eu-west-1.amazonaws.com/ur-support-site/118926/URSim_Linux-5.11.1.108318.tar.gz"
      - name: Push to dockerhub
        run: |
          docker push ${{secrets.DOCKER_USER}}/ursim_docker:$VERSION
        env:
          VERSION: 5.11.1.108318
          URSIM: "https://s3-eu-west-1.amazonaws.com/ur-support-site/118926/URSim_Linux-5.11.1.108318.tar.gz"