name: g3 Image CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Build dockerfile
        run: |
          docker build ursim/g3 --build-arg VERSION=$VERSION --build-arg URSIM=$URSIM
        env:
          VERSION: 3.15.3.106223
          URSIM: "https://s3-eu-west-1.amazonaws.com/ur-support-site/116229/URSim_Linux-3.15.3.106223.tar.gz"

  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: |
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build dockerfile
        run: |
          docker build ursim/g3 --build-arg VERSION=$VERSION --build-arg URSIM=$URSIM --tag ${{secrets.DOCKER_USER}}/ursim_docker:$VERSION
        env:
          VERSION: 3.15.3.106223
          URSIM: "https://s3-eu-west-1.amazonaws.com/ur-support-site/116229/URSim_Linux-3.15.3.106223.tar.gz"
      - name: Push to dockerhub
        run: |
          docker push ${{secrets.DOCKER_USER}}/ursim_docker:$VERSION
        env:
          VERSION: 3.15.3.106223
          URSIM: "https://s3-eu-west-1.amazonaws.com/ur-support-site/116229/URSim_Linux-3.15.3.106223.tar.gz"
